"""Trace, tool-routing, and deterministic-context blocks for the agent example."""

from .agent_loop import AgentLoop, AgentLoopOutcome, MAX_TOOL_CALLS_PER_TASK
from .checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    COMPLETED_PHASE,
    RESUMABLE_PHASE,
    CheckpointContractError,
    CheckpointError,
    CheckpointRecord,
    CheckpointResumeError,
    CheckpointStore,
    CheckpointStoreError,
    CompletedCheckpoint,
    FileCheckpointStore,
    ResumableCheckpoint,
    checkpoint_from_dict,
    checkpoint_from_json,
)
from .context import (
    ContextBuilder,
    ContextState,
    Evidence,
    EvidenceKind,
    ModelInput,
    RepositoryHint,
    ToolSchema,
    build_context,
)
from .events import (
    FinalAnswer,
    ModelRequest,
    ModelResult,
    Session,
    Step,
    ToolCall,
    ToolResult,
)
from .final_answer_evidence import (
    FinalAnswerEvidenceValidation,
    collect_allowed_final_answer_evidence,
    validate_final_answer_evidence,
)
from .incident_extraction import (
    FakeIncidentFieldExtractor,
    IncidentExtractionCandidate,
    IncidentExtractionResult,
    IncidentExtractionValidationError,
    IncidentFieldExtractor,
    IncidentInput,
    IncidentSource,
    IncidentSourceType,
    SourcedIncidentValue,
    extract_incident_fields,
    validate_incident_extraction,
)
from .model_boundary import (
    FakeModel,
    FinalAnswerCitation,
    FinalAnswerDecision,
    ModelClient,
    ModelDecision,
    ToolCallDecision,
)
from .model_errors import (
    InvalidModelOutputError,
    ModelBoundaryError,
    ModelExecutionError,
    ModelTimeoutError,
)
from .openai_model import (
    OpenAIModel,
    build_final_answer_response_format,
    build_messages,
    build_tools,
)
from .repository_resolver import RepositoryAliasResolver
from .trace import TraceRecorder
from .traced_model import TracedModelClient
from .tool_step import (
    ToolCallExecutor,
    ToolStepInvariantError,
    ToolStepExecutor,
    ToolStepOutcome,
)
from .tool_router import (
    ALLOWED_TOOL_NAMES,
    GET_FILE_CONTEXT,
    SEARCH_CODE,
    GetFileContextArguments,
    PydanticToolAdapter,
    Router,
    SearchCodeArguments,
    ToolCallResolutionError,
    ToolCallResolver,
    ToolDefinition,
    ToolErrorCode,
    ToolRouter,
    ToolValidationError,
)

__all__ = [
    "AgentLoop",
    "AgentLoopOutcome",
    "CHECKPOINT_SCHEMA_VERSION",
    "COMPLETED_PHASE",
    "CheckpointContractError",
    "CheckpointError",
    "CheckpointRecord",
    "CheckpointResumeError",
    "CheckpointStore",
    "CheckpointStoreError",
    "CompletedCheckpoint",
    "ContextBuilder",
    "ContextState",
    "Evidence",
    "EvidenceKind",
    "FakeModel",
    "FinalAnswer",
    "FinalAnswerCitation",
    "FinalAnswerDecision",
    "FinalAnswerEvidenceValidation",
    "FakeIncidentFieldExtractor",
    "FileCheckpointStore",
    "ALLOWED_TOOL_NAMES",
    "GET_FILE_CONTEXT",
    "GetFileContextArguments",
    "InvalidModelOutputError",
    "IncidentExtractionCandidate",
    "IncidentExtractionResult",
    "IncidentExtractionValidationError",
    "IncidentFieldExtractor",
    "IncidentInput",
    "IncidentSource",
    "IncidentSourceType",
    "MAX_TOOL_CALLS_PER_TASK",
    "ModelBoundaryError",
    "ModelClient",
    "ModelExecutionError",
    "ModelTimeoutError",
    "ModelInput",
    "ModelDecision",
    "ModelRequest",
    "ModelResult",
    "OpenAIModel",
    "PydanticToolAdapter",
    "RepositoryAliasResolver",
    "RepositoryHint",
    "RESUMABLE_PHASE",
    "ResumableCheckpoint",
    "Router",
    "SEARCH_CODE",
    "SearchCodeArguments",
    "Session",
    "Step",
    "SourcedIncidentValue",
    "ToolCallResolutionError",
    "ToolCallResolver",
    "ToolCall",
    "ToolCallDecision",
    "ToolCallExecutor",
    "ToolDefinition",
    "ToolErrorCode",
    "ToolRouter",
    "ToolSchema",
    "ToolStepExecutor",
    "ToolStepInvariantError",
    "ToolStepOutcome",
    "ToolResult",
    "ToolValidationError",
    "TraceRecorder",
    "TracedModelClient",
    "build_context",
    "build_final_answer_response_format",
    "build_messages",
    "build_tools",
    "checkpoint_from_dict",
    "checkpoint_from_json",
    "collect_allowed_final_answer_evidence",
    "extract_incident_fields",
    "validate_incident_extraction",
    "validate_final_answer_evidence",
]
